---

env:
  - ACTION=validate
    SSH_PUBLIC_KEY=${TRAVIS_BUILD_DIR}/fake_for_test

matrix:
  include:
    - dist: trusty


branches:
  only:
    - master

language: bash
sudo: enabled

script:
  - touch $SSH_PUBLIC_KEY && bash build.sh
